import assert from "node:assert/strict";
import { randomUUID, createHash } from "node:crypto";
import { PDFDocument } from "pdf-lib";
import { NextRequest } from "next/server";
import { prisma } from "../src/lib/prisma";
import { createSessionValue, SESSION_COOKIE } from "../src/lib/auth";
import { bindTestCookies } from "../src/lib/requestCookies";
import { GET, POST } from "../src/app/api/intakes/[id]/document-reviews/route";
import { POST as addCorrection } from "../src/app/api/intakes/[id]/document-reviews/corrections/route";
import { PATCH } from "../src/app/api/intakes/[id]/document-reviews/corrections/[correctionId]/route";
import { GET as readPdf } from "../src/app/api/intakes/[id]/document-reviews/[reviewId]/pdf/route";
import { GET as dashboard } from "../src/app/api/document-corrections/route";
import { DELETE as deleteProvider } from "../src/app/api/master/providers/[id]/route";
import { saveFile, readFile, deleteFile, fileExists } from "../src/lib/storage";
import { extractPdfText } from "../src/lib/pdfText";

async function main() {
  assert.match(process.env.DATABASE_URL || "", /document-review-tests\.db$/);
  const tag = randomUUID();
  const files: string[] = [];
  const req = (method = "GET", body?: unknown, url = "http://localhost/api/test") => new NextRequest(url, { method, ...(body === undefined ? {} : { headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }) });
  const success = async (response: Response, status = 200) => { const body = await response.json(); assert.equal(response.status, status, JSON.stringify(body)); return body; };
  try {
    const a = await prisma.provider.create({ data: { name: "Synthetic Adobe A", slug: `adobe-a-${tag}` } });
    const b = await prisma.provider.create({ data: { name: "Synthetic Adobe B", slug: `adobe-b-${tag}` } });
    const user = async (providerId: string, role: string, active = true) => prisma.user.create({ data: { name: `Synthetic ${role}`, email: `${randomUUID()}@example.invalid`, passwordHash: "not-a-login", memberships: { create: { providerId, role, active } } } });
    const actor = await user(a.id, "STAFF"); const owner = await user(a.id, "PROVIDER_ADMIN");
    const reviewer = await user(a.id, "REVIEWER"); const inactive = await user(a.id, "STAFF", false); const outsider = await user(b.id, "STAFF");
    const createIntake = async (providerId: string) => prisma.intake.create({ data: { provider: { connect: { id: providerId } }, token: randomUUID(), tokenExpiresAt: new Date(Date.now() + 86400000), client: { create: { providerId, fullName: "Synthetic Adobe Client", dob: "1990-01-01" } } } });
    const intake = await createIntake(a.id); const other = await createIntake(b.id);
    const params = { params: Promise.resolve({ id: intake.id }) };
    const signIn = (id?: string) => bindTestCookies({ get: name => name === SESSION_COOKIE && id ? { value: createSessionValue(id) } : undefined });
    const pdf = await PDFDocument.create(); pdf.addPage().drawText("SYNTHETIC ADOBE REVIEW TEST ONLY");
    const original = Buffer.from(await pdf.save());
    const originalPath = `document-review-tests/${tag}/original.pdf`; files.push(originalPath); saveFile(originalPath, original);
    const packet = await prisma.generatedPdf.create({ data: { intakeId: intake.id, filePath: originalPath, contentRevision: 1 } });
    const otherPacket = await prisma.generatedPdf.create({ data: { intakeId: other.id, filePath: originalPath, contentRevision: 1 } });
    signIn(); assert.equal((await GET(req(), params)).status, 401);
    signIn(outsider.id); assert.equal((await GET(req(), params)).status, 404);
    signIn(reviewer.id); assert.equal((await POST(req("POST", { expectedContentRevision: 1, sourcePacketId: packet.id }), params)).status, 403);
    signIn(actor.id);
    assert.equal((await POST(req("POST", { expectedContentRevision: 1, sourcePacketId: otherPacket.id }), params)).status, 404, "No cross-intake packet access");
    assert.equal((await POST(req("POST", { expectedContentRevision: 2, sourcePacketId: packet.id }), params)).status, 409);
    assert.equal((await POST(req("POST", { expectedContentRevision: 1, filePath: originalPath }), params)).status, 400);
    assert.equal((await POST(req("POST", { expectedContentRevision: 1 }), params)).status, 409, "Draft requires an approved provider template");
    const saved = await success(await POST(req("POST", { expectedContentRevision: 1, sourcePacketId: packet.id }), params), 201);
    const review = await prisma.documentReview.findUniqueOrThrow({ where: { id: saved.id } }); files.push(review.filePath);
    assert.deepEqual(readFile(review.filePath), original, "Saved generated packet is copied byte-for-byte");
    assert.equal(review.sha256, createHash("sha256").update(original).digest("hex"));
    const pdfParams = { params: Promise.resolve({ id: intake.id, reviewId: review.id }) };
    const fileResponse = await readPdf(req(), pdfParams);
    assert.equal(fileResponse.status, 200); assert.match(fileResponse.headers.get("cache-control") || "", /no-store/);
    assert.deepEqual(Buffer.from(await fileResponse.arrayBuffer()), original);
    for (const assignedUserId of [outsider.id, reviewer.id, inactive.id]) assert.equal((await addCorrection(req("POST", { reviewId: review.id, page: 1, comment: "Synthetic correction", assignedUserId }), params)).status, 400);
    assert.equal((await addCorrection(req("POST", { reviewId: review.id, page: 2, comment: "Synthetic correction", assignedUserId: owner.id }), params)).status, 400);
    let correction = await success(await addCorrection(req("POST", { reviewId: review.id, page: 1, comment: "Check the synthetic intake date.", assignedUserId: owner.id }), params), 201);
    const patchParams = { params: Promise.resolve({ id: intake.id, correctionId: correction.id }) };
    signIn(reviewer.id); assert.equal((await PATCH(req("PATCH", { expectedRevision: 1, status: "OPEN" }), patchParams)).status, 403);
    signIn(outsider.id); assert.equal((await readPdf(req(), pdfParams)).status, 404); assert.equal((await PATCH(req("PATCH", { expectedRevision: 1, status: "OPEN" }), patchParams)).status, 404);
    assert.equal((await dashboard(req("GET", undefined, `http://localhost/api/document-corrections?providerId=${a.id}`))).status, 403);
    signIn(actor.id);
    const list = await success(await GET(req(), params));
    assert(!JSON.stringify(list.versions).includes("filePath"), "Storage paths stay private");
    assert.equal(list.corrections[0].ownerActive, true);
    assert.equal((await PATCH(req("PATCH", { expectedRevision: 1, status: "RESOLVED" }), patchParams)).status, 400);
    correction = await success(await PATCH(req("PATCH", { expectedRevision: 1, status: "RESOLVED", resolutionNote: "Verified against synthetic source." }), patchParams));
    assert.equal(correction.revision, 2);
    assert.equal((await PATCH(req("PATCH", { expectedRevision: 1, assignedUserId: actor.id }), patchParams)).status, 409, "Second browser cannot overwrite the first browser's resolution");
    const immutable = await prisma.documentReview.findUniqueOrThrow({ where: { id: review.id } });
    assert.deepEqual(immutable, review); assert.deepEqual(readFile(originalPath), original);
    assert.equal((await prisma.intake.findUniqueOrThrow({ where: { id: intake.id } })).contentRevision, 1, "Review notes do not change clinical content or signatures");
    correction = await success(await PATCH(req("PATCH", { expectedRevision: 2, status: "OPEN" }), patchParams));
    assert.equal(correction.resolutionNote, null);
    const event = await prisma.auditLog.findFirstOrThrow({ where: { intakeId: intake.id, event: "document_correction_updated", detail: { contains: '"previous":{"status":"RESOLVED"' } } });
    assert(event.detail?.includes("Verified against synthetic source."), "Reopening preserves the old resolution in the audit trail");
    await prisma.userMembership.update({ where: { userId_providerId: { userId: owner.id, providerId: a.id } }, data: { active: false } });
    const pending = await success(await dashboard(req("GET", undefined, `http://localhost/api/document-corrections?providerId=${a.id}`)));
    assert.equal(pending.total, 1); assert.equal(pending.corrections[0].ownerActive, false);
    await prisma.intake.update({ where: { id: intake.id }, data: { contentRevision: 2 } });
    const history = await success(await GET(req(), params)); assert.equal(history.versions[0].contentRevision, 1); assert.equal(history.contentRevision, 2);
    saveFile(review.filePath, Buffer.from("corrupted synthetic file"));
    assert.equal((await readPdf(req(), pdfParams)).status, 409, "Fingerprint mismatch fails closed"); saveFile(review.filePath, original);
    // Approved synthetic template enables draft review before signatures or completion.
    await prisma.pdfTemplate.create({ data: { providerId: a.id, name: `Synthetic Adobe Template ${tag}`, filePath: originalPath, originalFileName: "synthetic-adobe.pdf", pageCount: 1, pageWidth: 612, pageHeight: 792, isActive: true, mappingStatus: "APPROVED", mappingScore: 100, approvedAt: new Date(), fieldMappings: { create: [{ fieldKey: "synthetic_name", page: 1, data: JSON.stringify({ source: "client_full_name", type: "text", x: 40, y: 680, width: 400, height: 20, fontSize: 12, required: false }) }] } } });
    const draftResult = await success(await POST(req("POST", { expectedContentRevision: 2 }), params), 201);
    const draft = await prisma.documentReview.findUniqueOrThrow({ where: { id: draftResult.id } }); files.push(draft.filePath);
    assert.equal(draft.source, "DRAFT"); assert.equal(draft.contentRevision, 2);
    assert((await extractPdfText(readFile(draft.filePath))).includes("DRAFT REVIEW COPY"));
    assert.equal(await prisma.generatedPdf.count({ where: { intakeId: intake.id } }), 1, "Draft review does not create a final packet");
    assert.equal(await prisma.signature.count({ where: { intakeId: intake.id } }), 0);
    assert.equal(await prisma.messageDelivery.count(), 0, "Review workflow sends no messages");
    await prisma.user.update({ where: { id: actor.id }, data: { role: "master" } });
    const deletion = await deleteProvider(req("DELETE", { confirmName: a.name }), { params: Promise.resolve({ id: a.id }) });
    assert.equal(deletion.status, 200); assert(!fileExists(review.filePath)); assert(!fileExists(draft.filePath));
    assert(fileExists(originalPath), "Other provider's shared source remains intact");
    assert.equal(await prisma.documentCorrection.count(), 0);
    console.log("Document reviews: provider/read-only boundaries, immutable files, draft watermark, assigned corrections, conflict rejection, audit history, dashboard scope, fingerprint checks and safe deletion passed.");
  } finally {
    bindTestCookies(null);
    for (const file of files) deleteFile(file);
    await prisma.$disconnect();
  }
}
main().catch(error => { console.error(error); process.exitCode = 1; });
