import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { randomUUID, createHmac } from "node:crypto";
import bcrypt from "bcryptjs";
import { NextRequest } from "next/server";
import { isolatedSqlite } from "./isolatedSqlite";

async function main() {
  const database = isolatedSqlite("admin-destructive-actions-tests.db");
  database.pushSchema(fs.readFileSync("prisma/schema.prisma", "utf8"), "current-schema.prisma");
  process.env.DATABASE_URL = database.databaseUrl;
  process.env.SESSION_SECRET = "synthetic-admin-actions-session-only";
  process.env.MASTER_LOGIN_RESET_TOKEN = "";
  const realFetch = globalThis.fetch;
  globalThis.fetch = async () => { throw new Error("Admin regression tests must not contact an external service."); };
  const { prisma } = await import("../src/lib/prisma");
  const { bindTestCookies } = await import("../src/lib/requestCookies");
  const { createSessionValue, verifySessionValue, currentUser, SESSION_COOKIE } = await import("../src/lib/auth");
  const { requireStaff } = await import("../src/lib/staffGuard");
  const { POST: login } = await import("../src/app/api/auth/login/route");
  const { POST: emergencyReset } = await import("../src/app/api/internal/master-login-reset/route");
  const { PATCH: resetProvider, DELETE: deleteProvider } = await import("../src/app/api/master/providers/[id]/route");
  const { PATCH: resetStaff } = await import("../src/app/api/staff/users/[userId]/route");
  const { deleteFile } = await import("../src/lib/storage");
  const tag = randomUUID();
  const fileRoot = path.resolve("storage/admin-action-tests", tag);
  const outsideFile = path.join(database.directory, "outside-storage-sentinel.txt");
  const request = (url: string, method: string, body?: unknown, headers: Record<string, string> = {}) => new NextRequest(`http://localhost${url}`, { method, headers: { "content-type": "application/json", ...headers }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
  const oldPassword = "SyntheticOld2026!", newPassword = "SyntheticNew2026!";
  const makeLogin = (email: string, password: string, portal: "provider" | "master" = "provider") => login(request("/api/auth/login", "POST", { email, password, portal }));
  const signIn = (id: string | null) => bindTestCookies({ get: (name) => name === SESSION_COOKIE && id ? { value: createSessionValue(id) } : undefined });
  const useCookie = (value: string) => bindTestCookies({ get: (name) => name === SESSION_COOKIE ? { value } : undefined });
  try {
    fs.mkdirSync(fileRoot, { recursive: true });
    fs.writeFileSync(outsideFile, "SYNTHETIC OUTSIDE STORAGE SENTINEL");
    const a = await prisma.provider.create({ data: { name: "Synthetic Delete Target", slug: `delete-a-${tag}` } });
    const b = await prisma.provider.create({ data: { name: "Synthetic Preserved Provider", slug: `delete-b-${tag}` } });
    const passwordHash = await bcrypt.hash(oldPassword, 4);
    const master = await prisma.user.create({ data: { email: "admin@mooredivinecare.local", name: "Synthetic Master", passwordHash, role: "master" } });
    const admin = await prisma.user.create({ data: { email: "synthetic-admin@example.invalid", name: "Synthetic Provider Admin", passwordHash, memberships: { create: { providerId: a.id, role: "PROVIDER_ADMIN" } } } });
    const outsider = await prisma.user.create({ data: { email: "synthetic-outsider@example.invalid", name: "Synthetic Other Admin", passwordHash, memberships: { create: { providerId: b.id, role: "PROVIDER_ADMIN" } } } });
    const reset = (body: unknown, providerId = a.id) => resetProvider(request(`/api/master/providers/${providerId}`, "PATCH", body), { params: Promise.resolve({ id: providerId }) });
    const remove = (body: unknown) => deleteProvider(request(`/api/master/providers/${a.id}`, "DELETE", body), { params: Promise.resolve({ id: a.id }) });
    const resetBody = { adminEmail: admin.email, adminName: admin.name, adminPassword: newPassword };
    signIn(null);
    assert.equal((await reset(resetBody)).status, 401);
    assert.equal((await remove({ confirmName: a.name })).status, 401);
    signIn(admin.id);
    assert.equal((await reset(resetBody)).status, 403);
    assert.equal((await remove({ confirmName: a.name })).status, 403);
    signIn(master.id);
    assert.equal((await reset({ adminEmail: admin.email })).status, 400);
    assert.equal((await reset({ ...resetBody, adminPassword: "short" })).status, 400);
    assert.equal((await reset({ ...resetBody, adminEmail: master.email })).status, 409);
    assert.equal((await reset({ ...resetBody, adminEmail: outsider.email })).status, 409);
    assert.equal((await reset(resetBody, randomUUID())).status, 404);
    assert.equal((await prisma.user.findUniqueOrThrow({ where: { id: admin.id } })).passwordHash, passwordHash);
    const beforeResetLogin = await makeLogin(admin.email, oldPassword);
    assert.equal(beforeResetLogin.status, 200);
    const oldCookie = beforeResetLogin.cookies.get(SESSION_COOKIE)!.value;
    const legacyPayload = `${admin.id}.${Date.now() + 60000}`;
    const legacyCookie = `${legacyPayload}.${createHmac("sha256", process.env.SESSION_SECRET!).update(legacyPayload).digest("base64url")}`;
    useCookie(legacyCookie);
    assert.equal((await currentUser())?.id, admin.id, "a deploy preserves valid pre-version cookies before reset");
    assert.equal(verifySessionValue(`${oldCookie}tampered`), null);
    signIn(master.id);
    assert.equal((await reset(resetBody)).status, 200);
    assert.equal((await makeLogin(admin.email, oldPassword)).status, 401, "old password is rejected after reset");
    const afterResetLogin = await makeLogin(admin.email, newPassword);
    assert.equal(afterResetLogin.status, 200);
    assert.equal((await afterResetLogin.json()).destination, "/dashboard");
    const resetUser = await prisma.user.findUniqueOrThrow({ where: { id: admin.id } });
    assert.equal(resetUser.role, "staff");
    assert.equal(await bcrypt.compare(newPassword, resetUser.passwordHash), true);
    assert.notEqual(resetUser.passwordHash, newPassword);
    useCookie(afterResetLogin.cookies.get(SESSION_COOKIE)!.value);
    assert.equal((await requireStaff({ providerId: a.id })).deny, null);
    assert.equal((await requireStaff({ providerId: b.id })).deny?.status, 403);
    useCookie(oldCookie);
    assert.equal(await currentUser(), null, "reset must invalidate sessions issued under the previous password");
    useCookie(legacyCookie);
    assert.equal(await currentUser(), null, "reset must also revoke legacy cookies");
    console.log("Provider password reset: validation, authorization, cross-provider/master protection, old/new login and session revocation passed.");

    const masterReset = (password: string, token?: string) => emergencyReset(request("/api/internal/master-login-reset", "POST", { password }, token ? { "x-reset-token": token } : {}));
    assert.equal((await masterReset(newPassword, "synthetic-token")).status, 404, "emergency reset is disabled by default");
    process.env.MASTER_LOGIN_RESET_TOKEN = "synthetic-token";
    assert.equal((await masterReset(newPassword)).status, 404);
    assert.equal((await masterReset(newPassword, "wrong-token")).status, 404);
    assert.equal((await masterReset("short", "synthetic-token")).status, 400);
    const masterOldLogin = await makeLogin(master.email, oldPassword);
    assert.equal(masterOldLogin.status, 200);
    assert.equal((await masterReset(newPassword, "synthetic-token")).status, 200);
    assert.equal((await makeLogin(master.email, oldPassword)).status, 401);
    const providerMasterLogin = await makeLogin(master.email, newPassword);
    assert.equal((await providerMasterLogin.json()).destination, "/dashboard", "Provider portal retains the requested workspace for master users");
    const newMasterLogin = await makeLogin(master.email, newPassword, "master");
    assert.equal(newMasterLogin.status, 200);
    assert.equal((await newMasterLogin.json()).destination, "/master/dashboard");
    useCookie(masterOldLogin.cookies.get(SESSION_COOKIE)!.value);
    assert.equal(await currentUser(), null, "emergency reset must also invalidate old master sessions");
    useCookie(newMasterLogin.cookies.get(SESSION_COOKIE)!.value);
    process.env.MASTER_LOGIN_RESET_TOKEN = "";
    console.log("Emergency master reset: disabled/missing/wrong token, short password, new login and old-session revocation passed.");

    const staff = await prisma.user.create({ data: { email: "synthetic-staff@example.invalid", name: "Synthetic Staff", passwordHash, memberships: { create: { providerId: a.id, role: "STAFF" } } } });
    await prisma.userMembership.create({ data: { userId: master.id, providerId: a.id, role: "PROVIDER_ADMIN" } });
    await prisma.userMembership.create({ data: { userId: outsider.id, providerId: a.id, role: "STAFF" } });
    const resetStaffPassword = (userId: string, password = newPassword) => resetStaff(request(`/api/staff/users/${userId}`, "PATCH", { password }), { params: Promise.resolve({ userId }) });
    // Explicit provider context prevents falling back to another membership.
    const adminCookie = afterResetLogin.cookies.get(SESSION_COOKIE)!.value;
    bindTestCookies({ get: (name) => name === SESSION_COOKIE ? { value: adminCookie } : name === "mdc_provider" ? { value: a.id } : undefined });
    assert.equal((await resetStaffPassword(master.id)).status, 409, "provider staff settings cannot reset a master login");
    assert.equal((await resetStaffPassword(outsider.id)).status, 409, "provider staff settings cannot reset a shared account's password");
    assert.equal((await resetStaffPassword(staff.id, "short")).status, 400);
    const oldStaffLogin = await makeLogin(staff.email, oldPassword);
    assert.equal(oldStaffLogin.status, 200);
    assert.equal((await resetStaffPassword(staff.id)).status, 200);
    assert.equal((await makeLogin(staff.email, oldPassword)).status, 401);
    assert.equal((await makeLogin(staff.email, newPassword)).status, 200);
    useCookie(oldStaffLogin.cookies.get(SESSION_COOKIE)!.value);
    assert.equal(await currentUser(), null);
    useCookie(newMasterLogin.cookies.get(SESSION_COOKIE)!.value);
    console.log("Provider staff reset: master/shared-account protection, invalid password and old/new login/session revocation passed.");

    const makeClient = (providerId: string) => prisma.client.create({ data: { providerId, fullName: "Synthetic Deletion Client", dob: "1991-02-03" } });
    const clientA = await makeClient(a.id), clientB = await makeClient(b.id);
    const intakeA = await prisma.intake.create({ data: { providerId: a.id, clientId: clientA.id, token: randomUUID(), tokenExpiresAt: new Date(Date.now() + 86_400_000), copyToken: randomUUID(), copyTokenExpiresAt: new Date(Date.now() + 86_400_000) } });
    const intakeB = await prisma.intake.create({ data: { providerId: b.id, clientId: clientB.id, token: randomUUID(), tokenExpiresAt: new Date(Date.now() + 86_400_000) } });
    const relativeFile = (name: string) => `admin-action-tests/${tag}/${name}`;
    for (const name of ["template-a.pdf", "shared-template.pdf", "packet-a.pdf", "upload-a.pdf", "keep-b.pdf"]) fs.writeFileSync(path.join(fileRoot, name), `SYNTHETIC ${name}`);
    const templateA = await prisma.pdfTemplate.create({ data: { name: `A-${tag}`, providerId: a.id, filePath: relativeFile("template-a.pdf"), pageCount: 1, fieldMappings: { create: { fieldKey: "test", page: 1, data: "{}" } } } });
    await prisma.pdfTemplate.create({ data: { name: `A-shared-${tag}`, providerId: a.id, filePath: relativeFile("shared-template.pdf"), pageCount: 1 } });
    fs.symlinkSync(fileRoot, path.join(fileRoot, "shared-link"), process.platform === "win32" ? "junction" : "dir");
    await prisma.pdfTemplate.create({ data: { name: `B-shared-${tag}`, providerId: b.id, filePath: path.join(fileRoot, "shared-link/shared-template.pdf"), pageCount: 1 } });
    await prisma.generatedPdf.create({ data: { intakeId: intakeA.id, filePath: relativeFile("packet-a.pdf") } });
    await prisma.generatedPdf.create({ data: { intakeId: intakeB.id, filePath: relativeFile("keep-b.pdf") } });
    await prisma.uploadedDocument.create({ data: { intakeId: intakeA.id, fileName: "SYNTHETIC.pdf", filePath: relativeFile("upload-a.pdf"), mimeType: "application/pdf", docType: "other" } });
    await prisma.intakeAnswer.create({ data: { intakeId: intakeA.id, key: "synthetic", value: '"test"' } });
    await prisma.intakeSection.create({ data: { intakeId: intakeA.id, sectionKey: "synthetic" } });
    await prisma.signature.create({ data: { intakeId: intakeA.id, role: "client", imageData: "typed:SYNTHETIC", printedName: "SYNTHETIC", signedDate: "2026-09-06" } });
    await prisma.releaseConsent.create({ data: { intakeId: intakeA.id, slot: 1, recipient: "SYNTHETIC", items: "[]" } });
    await prisma.referral.create({ data: { intakeId: intakeA.id, slot: 1, name: "SYNTHETIC" } });
    await prisma.emergencyContact.create({ data: { intakeId: intakeA.id, slot: 1, name: "SYNTHETIC" } });
    await prisma.medication.create({ data: { intakeId: intakeA.id, name: "SYNTHETIC" } });
    await prisma.substanceUseRow.create({ data: { intakeId: intakeA.id, slot: 1, name: "SYNTHETIC" } });
    await prisma.treatmentPlanSignatureRow.create({ data: { intakeId: intakeA.id, slot: 1 } });
    await prisma.intakeFollowUp.create({ data: { intakeId: intakeA.id, token: randomUUID(), fieldKeys: "[]", tokenExpiresAt: new Date(Date.now() + 86_400_000) } });
    await prisma.workflowInterval.create({ data: { intakeId: intakeA.id, stage: "SYNTHETIC" } });
    await prisma.directoryStewardship.create({ data: { providerId: a.id, directoryVersion: "synthetic", action: "ASSIGN", ownerUserId: admin.id, ownerName: "SYNTHETIC", actorUserId: master.id, actorName: "SYNTHETIC" } });
    const referral = await prisma.supportReferral.create({ data: { providerId: a.id, intakeId: intakeA.id, resourceId: "synthetic", resourceName: "SYNTHETIC", resourceUrl: "https://example.invalid", category: "test", assignedUserId: admin.id } });
    await prisma.supportReferralEvent.create({ data: { providerId: a.id, intakeId: intakeA.id, referralId: referral.id, actorUserId: master.id, kind: "CREATED", toStatus: "SUGGESTED", revision: 1, detailsJson: "{}" } });
    await prisma.ncTracksConfiguration.create({ data: { providerId: a.id, authorizedNpi: "1134943608" } });
    const host = await prisma.ncTracksHost.create({ data: { providerId: a.id, name: "SYNTHETIC HOST", credentialHash: randomUUID(), expiresAt: new Date(Date.now() + 86_400_000) } });
    await prisma.ncTracksJob.create({ data: { providerId: a.id, intakeId: intakeA.id, hostId: host.id, requestedByUserId: master.id, idempotencyKey: tag, dedupKey: tag, identityFingerprint: tag, subjectJson: "{}", authorizedNpi: "1134943608", serviceDateFrom: "2026-09-06", serviceDateTo: "2026-09-06" } });
    const delivery = await prisma.messageDelivery.create({ data: { providerId: a.id, intakeId: intakeA.id, channel: "email", purpose: "synthetic", recipient: "***@example.invalid", status: "failed", isFinal: true } });
    const audit = await prisma.auditLog.create({ data: { providerId: a.id, intakeId: intakeA.id, userId: master.id, event: "synthetic_before_delete" } });
    const preserved = await prisma.provider.findUnique({ where: { id: b.id }, include: { clients: true, intakes: true, memberships: true, pdfTemplates: true } });
    for (const body of [{}, { confirmName: a.name.toLowerCase() }, { confirmName: `${a.name} ` }]) assert.equal((await remove(body)).status, 400);
    assert.equal(await prisma.intake.count({ where: { id: intakeA.id } }), 1);
    assert.equal(await prisma.ncTracksHost.count({ where: { id: host.id } }), 1);
    assert(fs.existsSync(path.join(fileRoot, "packet-a.pdf")), "failed confirmation preserves files");
    const deleted = await remove({ confirmName: a.name });
    assert.equal(deleted.status, 200, await deleted.clone().text());
    const deletedBody = await deleted.json();
    assert.equal(deletedBody.deleted.clients, 1);
    assert.equal(deletedBody.deleted.intakes, 1);
    assert.equal(deletedBody.deleted.supportReferralEvents, 1);
    const intakeModels = [prisma.intakeAnswer, prisma.intakeSection, prisma.signature, prisma.generatedPdf, prisma.uploadedDocument, prisma.releaseConsent, prisma.referral, prisma.emergencyContact, prisma.medication, prisma.substanceUseRow, prisma.treatmentPlanSignatureRow, prisma.intakeFollowUp, prisma.workflowInterval, prisma.supportReferral, prisma.supportReferralEvent, prisma.ncTracksJob];
    for (const model of intakeModels) assert.equal(await (model.count as unknown as (args: { where: { intakeId: string } }) => Promise<number>)({ where: { intakeId: intakeA.id } }), 0);
    assert.equal(await prisma.provider.count({ where: { id: a.id } }), 0);
    assert.equal(await prisma.client.count({ where: { id: clientA.id } }), 0);
    assert.equal(await prisma.pdfFieldMapping.count({ where: { templateId: templateA.id } }), 0);
    assert.equal(await prisma.userMembership.count({ where: { providerId: a.id } }), 0);
    assert.equal(await prisma.directoryStewardship.count({ where: { providerId: a.id } }), 0);
    assert.equal(await prisma.ncTracksConfiguration.count({ where: { providerId: a.id } }), 0);
    assert.equal(await prisma.ncTracksHost.count({ where: { id: host.id } }), 0, "deleted host credentials can no longer authenticate");
    assert.deepEqual(await prisma.provider.findUnique({ where: { id: b.id }, include: { clients: true, intakes: true, memberships: true, pdfTemplates: true } }), preserved);
    for (const name of ["template-a.pdf", "packet-a.pdf", "upload-a.pdf"]) assert.equal(fs.existsSync(path.join(fileRoot, name)), false);
    assert(fs.existsSync(path.join(fileRoot, "keep-b.pdf")));
    assert(fs.existsSync(path.join(fileRoot, "shared-template.pdf")), "provider deletion must preserve files referenced by another provider");
    assert.equal((await remove({ confirmName: a.name })).status, 404, "deletion retry is safe");
    const retainedAudit = await prisma.auditLog.findUniqueOrThrow({ where: { id: audit.id } });
    const retainedDelivery = await prisma.messageDelivery.findUniqueOrThrow({ where: { id: delivery.id } });
    assert.equal(retainedAudit.intakeId, null); assert.equal(retainedAudit.providerId, null);
    assert.equal(retainedDelivery.intakeId, null); assert.equal(retainedDelivery.providerId, null);
    assert.equal(await prisma.auditLog.count({ where: { event: "provider_profile_deleted" } }), 1);
    useCookie(afterResetLogin.cookies.get(SESSION_COOKIE)!.value);
    assert.equal((await requireStaff({ providerId: a.id })).deny?.status, 404, "deleted-provider administrator has no remaining access");
    assert.throws(() => deleteFile(outsideFile), /outside storage/);
    fs.symlinkSync(database.directory, path.join(fileRoot, "outside-link"), process.platform === "win32" ? "junction" : "dir");
    assert.throws(() => deleteFile(relativeFile("outside-link/outside-storage-sentinel.txt")), /outside storage/, "a storage junction cannot redirect deletion outside storage");
    assert.equal(fs.readFileSync(outsideFile, "utf8"), "SYNTHETIC OUTSIDE STORAGE SENTINEL");
    console.log("Permanent deletion: exact-name/auth rejection without changes, actual cascade across every intake child, NCTracks credentials/jobs, scoped files, preserved other provider/shared file, detached audit/delivery retention and retry passed.");
  } finally {
    bindTestCookies(null);
    globalThis.fetch = realFetch;
    await prisma.$disconnect();
    const target = path.resolve(fileRoot);
    assert.equal(path.dirname(target), path.resolve("storage/admin-action-tests"));
    assert.equal(path.basename(target), tag);
    if (fs.existsSync(path.join(target, "outside-link"))) fs.unlinkSync(path.join(target, "outside-link"));
    if (fs.existsSync(path.join(target, "shared-link"))) fs.unlinkSync(path.join(target, "shared-link"));
    fs.rmSync(target, { recursive: true, force: true });
    database.cleanup();
  }
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
